# Generated by Django 4.0.2 on 2022-02-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
