# Generated by Django 4.0.2 on 2022-02-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0003_remove_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='package_name',
            new_name='order_name',
        ),
    ]
