# Generated by Django 4.0.2 on 2022-02-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0003_rename_profile_pic_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(null=True),
        ),
    ]
