# Generated by Django 4.0.2 on 2022-02-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0004_rename_package_name_delivery_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
