# Generated by Django 4.0.2 on 2022-02-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0004_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
