# Generated by Django 4.0.2 on 2022-02-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0006_order_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='token',
        ),
        migrations.AddField(
            model_name='delivery',
            name='token',
            field=models.CharField(default='uYMVPS', max_length=6),
        ),
    ]
