# Generated by Django 4.0.2 on 2022-02-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0007_remove_order_token_delivery_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='order_name',
            new_name='remarks',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='token',
            field=models.CharField(default='HY9TFL', max_length=6),
        ),
    ]
