# Generated by Django 4.0.2 on 2022-02-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0009_alter_delivery_remarks_alter_delivery_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='token',
            field=models.CharField(default='MNLKQH', max_length=6),
        ),
        migrations.CreateModel(
            name='SpecialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.product')),
            ],
        ),
    ]
