name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8, 3.9 ]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: mysql
        ports: [ '3306:3306' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Migrations
        run: |
          python manage.py migrate
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_HOST: ${{ secrets.NULL }}
          DEFAULT_EMAIL_HOST: ${{ secrets.NULL }}
          EMAIL_PASS: ${{ secrets.NULL }}
          EMAIL_PROTOCOL: ${{ secrets.NULL}}
          DATABASE_NAME: mysql
          DATABASE_USER: root
          DATABASE_PASS: test
          DATABASE_HOST: 127.0.0.1
          DBPORT: $
      - name: Run Tests
        run: |
          coverage run manage.py test && coverage report --fail-under=75 && coverage xml
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_HOST: ${{ secrets.NULL }}
          DEFAULT_EMAIL_HOST: ${{ secrets.NULL }}
          EMAIL_PASS: ${{ secrets.NULL }}
          EMAIL_PROTOCOL: ${{ secrets.NULL}}
          DATABASE_NAME: mysql
          DATABASE_USER: root
          DATABASE_PASS: test
          DATABASE_HOST: 127.0.0.1
          DBPORT: $
      - name: Report Coverage
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_HOST: ${{ secrets.NULL }}
          DEFAULT_EMAIL_HOST: ${{ secrets.NULL }}
          EMAIL_PASS: ${{ secrets.NULL }}
          EMAIL_PROTOCOL: ${{ secrets.NULL}}
          DATABASE_NAME: mysql
          DATABASE_USER: root
          DATABASE_PASS: test
          DATABASE_HOST: 127.0.0.1
          DBPORT: $
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          directory: ./coverage/reports/
          fail_ci_if_error: true
          verbose: true
